### PR TITLE
Update README per CLOUD-214

### PR DESCRIPTION
**Pull request by psoloway**
* Add a note to the Reference section for each parameter that is
read-only after creation.
* Remove the CI Build Status as part of a site-wide shift to reduce
server load.

### CODE REVIEW

**Comment by pjfoley** [comment]
Some of these parameters should be changeable after creation.  Is this just to reflect the way the types and providers currently work?

For example #137

**Comment by garethr** [comment]
@pjfoley yes, you're correct. This documentation change is just updating the docs to represent how things currently work.

**Comment by garethr** [comment]
Hi @psoloway. The main README changes look good.

If you could just change the commit message. Ideally it should follow the format:

    (CLOUD-XXX) details of why the change was made

The backlog isn't public and it's useful to have the why if you're going through the commit log.

I'm definitely not in favour of removing the travis indicator however. The commit mentions this in passing as reducing load, but the load here is on Travis. This visibility is very important to anyone involved in the development. If you could remove that from this commit at least and maybe grab me to discuss.

**Comment by garethr** [comment]
Closed in https://github.com/puppetlabs/puppetlabs-aws/commit/7c9bfae473e5f4a74ea426c923a440558d472e80 after talking with @jbondpdx

**Pull request closed without merging**
