### PR TITLE
Add visibility_timeout to sqs_queue

### LINKED ISSUE #344: sqs_queue type is missing visibility timeout
It would be nice to have `VisibilityTimeout` queue attribute - http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AboutVT.html

### PR DESCRIPTION
**Pull request by s12v**
Fixes #344

### CODE REVIEW

**Comment by s12v** [comment]
@hunner, would appreciate feedback on this :)

**Comment by zleswomp** [comment]
+1  The new property needs documentation in the README.

**Comment by s12v** [comment]
@zleswomp, updated readme

**Comment by zleswomp** [comment]
Thank you.  I'm still +1 here.

**Pull request merged**
