### PR TITLE
Properly handle array of domain_name for ec2_vpc_dhcp_options

### PR DESCRIPTION
**Pull request by edestecd**
The domain name should be a space separated list not a comma separated list.

### CODE REVIEW

**Comment by zleswomp** [comment]
Thank you for the PR.  Is there a README update that needs to be made for this change also?

**Comment by edestecd** [comment]
Yea, I should probably add some doc...

**Comment by edestecd** [comment]
@zleswomp Doc added.

**Comment by zleswomp** [comment]
This looks reasonable to me, though, have you been able to test this?  Does it work as desired?

**Comment by edestecd** [comment]
I ran it in our test vpc and created a few dhcp_options. It worked as expected and on successive puppet runs it was happy. There is a spec test to make sure the comparison works as well, so if thats passing I suspect thats a good indication as well.
https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/unit/type/ec2_vpc_dhcp_options_spec.rb#L58

I'm going to be using it tomorrow to build our production vpc...

**Comment by edestecd** [comment]
Can you think of any additional spec test we might want?

**Comment by edestecd** [comment]
@zleswomp what do you think? Anything else I can add?

**Comment by zleswomp** [comment]
Alright, I read over the docs for this.  This looks good to me.  Thanks for the contribution.

**Pull request merged**
