### PR TITLE
Remove contradictory attribute descriptions.

### LINKED ISSUE #388: Contadictory Documentation for ec2_vpc_subnet
The documentation for the `ec2_vpc_subnet` has two entries for the `region` attribute.  One says that the attribute is required and the other says that it is optional.  Testing seems to suggest that is is required.

### PR DESCRIPTION
**Pull request by dallinb**
Fixes #388.  While your at it, please can you take a look at my previous PR (#364).

### CODE REVIEW

**Comment by dallinb** [comment]
TravisCI is failing for Ruby 1.9.3 because webmock 2.3.1 requires Ruby >= 2.0.

**Comment by zleswomp** [comment]
https://github.com/puppetlabs/puppetlabs-aws/pull/390 for webmock.

**Comment by zleswomp** [comment]
+1

**Comment by dallinb** [comment]
Pulled in #390 provided by @zleswomp and tests are now passing.

**Pull request merged**
