### PR TITLE
Align testing with docs

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
It appears that travis needs to be associated with this repo

**Comment by ghoneycutt** [comment]
An interestingly odd assortment of platforms that pass testing.

https://travis-ci.org/ghoneycutt/puppetlabs-aws/builds/47440510

**Comment by garethr** [comment]
@ghoneycutt thanks for bugging me about this. I won't be able to merge this as is, as some parts (like the `location_for` helper are used on our internal Jenkins instance.

I'll sort out adding this back to travis as well based on some of these changes.

**Comment by garethr** [comment]
@ghoneycutt thanks again. I've updated everything to run in Travis https://travis-ci.org/puppetlabs/puppetlabs-aws under 2.1, 2.2 and 1.9.3, as well as under the future parser.

The mustache issue was caused by the release of 1.0 last week. https://github.com/mustache/mustache/commit/c4dff3f1ac0db70a8b4b90c906ead8b4a3e10f61

We've been focusing on the [acceptance tests](https://github.com/puppetlabs/puppetlabs-aws/tree/master/spec/acceptance) recently, but I'd like to come back to the unit tests at some point and make them more useful.

**Comment by ghoneycutt** [comment]
Totally understand. You should be able to cherry pick b99d8c285888be64f31c6c0bd4cfc1fa7aa3e3f4

**Pull request closed without merging**
