### PR TITLE
Add optional 'ssl_certificate_id' parameter to elb_loadbalancer

### PR DESCRIPTION
**Pull request by daveseff**
This is to satisfy part of #214 . This is an optional parameter if the protocol is HTTPS you can add the arn:: cert to your listener.

### CODE REVIEW

**Comment by DavidS** [comment]
Thank you for your contribution. Could you please talk to @benpillet over at #219 and get a unified version of this going?

**Comment by mentat** [comment]
Ping.

**Comment by daveseff** [comment]
@benpillet and @DavidS What else needs to be done here? I see the NeedsDocs tag but I've already updated the readme, which seems to be the only "docs" that this module has.

**Comment by DavidS** [comment]
@daveseff something weird's going on with this PR, most of the commits listed are already in master. Can you have a look and cleanup/rebase that? It's pretty hard to review as is.

**Comment by daveseff** [comment]
@DavidS Ok I've rebased again. Can you please review?

**Comment by DavidS** [comment]
Thanks for your contribution!

**Pull request merged**
