### PR TITLE
AWS supports ingress rules for specific ICMP types.

### PR DESCRIPTION
**Pull request by daveseff**
Fixes upstream issue #266

### CODE REVIEW

**Comment by danielparks** [comment]
+1

**Comment by danieldreier** [comment]
+1; @garethr do you think this needs further discussion / test coverage or can we just merge?

**Comment by daveseff** [comment]
@DavidS Any chance this can get merged?

**Comment by danielparks** [comment]
@garethr @DavidS ping?

**Comment by zleswomp** [comment]
By the power vested in me, I grant you the power to click merge.

**Comment by danielparks** [comment]
Sweeeet

**Pull request merged**
