### PR TITLE
Add docs for RDS DB subnet groups

### PR DESCRIPTION
**Pull request by zabacad**
This adds documentation for RDS DB subnet group resources. Support for these
was added recently.

### CODE REVIEW

**Comment by zabacad** [comment]
Support for these was added in #422.

Thanks @DoctahPopp871 for writing that code. Do these docs look all correct?

**Comment by zleswomp** [comment]
Great, thank you @zabacad.  This looks good to me.

**Comment by zabacad** [comment]
Updated:

- Adding missing underscore in type name.
- Description is required.

**Comment by DoctahPopp871** [comment]
This looks great ! @zabacad  thanks!

**Pull request merged**
