### PR TITLE
Enhance RDS instance functionality

### PR DESCRIPTION
**Pull request by zabacad**
- Fix new RDS instance tagging
- Improve creating RDS instances from snapshot
- Enhance RDS instance VPC SG support

### CODE REVIEW

**Comment by zabacad** [comment]
This covers #372 .

**Comment by zleswomp** [comment]
@zabacad Please rebase.

**Comment by zabacad** [comment]
Rebased.

**Comment by zleswomp** [comment]
This still looks good to me.  Merging.

**Pull request merged**
