### PR TITLE
Add ptr record support

### PR DESCRIPTION
**Pull request by cwood**

### CODE REVIEW

**Comment by garethr** [comment]
Hi @cwood. Thanks so much for adding this. Much appreciated. Would you be able to add the new type to the tests (you should be able to just add to https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/unit/type/route53_record_spec.rb) and to the documentation in the README: https://github.com/puppetlabs/puppetlabs-aws#types and https://github.com/puppetlabs/puppetlabs-aws#type-route53.

**Comment by cwood** [comment]
Yea I can do that and update. Really hoping this module gets far. I want to use this over terraform

**Comment by cwood** [comment]
Anything else that needs to happen?

**Comment by garethr** [comment]
Hi @cwood. Thanks for this, apolgies, I'd been travelling back to the UK. This looks good, much appreciated.

**Comment by cwood** [comment]
Thanks so much!

**Pull request merged**
