### PR TITLE
Allow snapshot to be specified in block mappings

### PR DESCRIPTION
**Pull request by cpick**
This change makes it possible to attach volumes based on snapshots to new ec2
instances.

### CODE REVIEW

**Comment by DavidS** [comment]
Hi Chris, this change looks good, but would clutter the git history in its current state. Please squash them together and repush here.

Squashing: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by DavidS** [comment]
It would also be good to add a short note to the README describing the new property.

**Comment by cpick** [comment]
Documented and squashed.  Should be good to go.

**Comment by DavidS** [comment]
Thank you for your contribution!

**Pull request merged**
