### PR TITLE
Add initial IAM resources

### PR DESCRIPTION
**Pull request by zleswomp**
This work adds new types and supporting providers for IAM user, group,
and policy management.  Without this change, there is no support for
managing the above resources in IAM using Puppet.

### CODE REVIEW

**Comment by zleswomp** [comment]
I'm fleshing out a bit of docs, but I'm not planning to change the code here.

**Comment by zleswomp** [comment]
I've updated the README.  Ready for review please.

**Comment by zleswomp** [comment]
Hi.  Anything else I can do here?

**Comment by binford2k** [comment]
@hunner think we can get a review on this?

**Comment by ngeorgieff** [comment]
Great work @zleswomp !

**Comment by danieldreier** [comment]
This looks very useful. Can we get it merged?

**Comment by zleswomp** [comment]
Dear friends, this code works for us.  Might we get a merge or perhaps some guidance on what needs improving to get it committed?

**Pull request merged**
